# Generated by Django 5.0.1 on 2024-07-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='pdf',
            field=models.FileField(upload_to='papers/upload/'),
        ),
    ]
