# Generated by Django 5.0.1 on 2024-07-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_alter_paper_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='pdf',
            field=models.FileField(upload_to='api/papers/'),
        ),
    ]
