# Generated by Django 5.0.7 on 2024-11-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_alter_paper_pdf'),
        ('papers', '0005_paper_number'),
    ]

    operations = [
    ]
