# Generated by Django 5.0.7 on 2024-07-22 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('memo_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='papers.paper')),
            ],
        ),
    ]
