# Generated by Django 5.0.1 on 2024-07-08 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0001_initial'),
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='paper',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='papers.paper'),
        ),
    ]
