# Generated by Django 5.0.7 on 2024-11-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0002_alter_memo_content'),
        ('memos', '0002_alter_memo_paper'),
    ]

    operations = [
    ]
