# Generated by Django 5.0.1 on 2024-07-07 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperInfo',
            fields=[
                ('paperInfo_id', models.AutoField(primary_key=True, serialize=False)),
                ('reference', models.TextField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.paper')),
            ],
        ),
    ]
