# Generated by Django 5.0.7 on 2024-07-22 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperInfo',
            fields=[
                ('paperInfo_id', models.AutoField(primary_key=True, serialize=False)),
                ('MLA', models.TextField(blank=True, null=True)),
                ('APA', models.TextField(blank=True, null=True)),
                ('Chicago', models.TextField(blank=True, null=True)),
                ('Vancouver', models.TextField(blank=True, null=True)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='papers.paper')),
            ],
        ),
    ]
