# Generated by Django 5.0.1 on 2024-07-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperinfos', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='paperinfo',
        #     name='reference',
        # ),
        migrations.AddField(
            model_name='paperinfo',
            name='apa_reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paperinfo',
            name='chicago_reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paperinfo',
            name='mla_reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paperinfo',
            name='vancouver_reference',
            field=models.TextField(blank=True, null=True),
        ),
    ]
