# Generated by Django 5.0.1 on 2024-07-12 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperinfos', '0003_remove_paperinfo_apa_reference_and_more'),
        ('papers', '0003_alter_paper_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperinfo',
            name='reference',
        ),
        migrations.AddField(
            model_name='paperinfo',
            name='apa_reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paperinfo',
            name='chicago_reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paperinfo',
            name='mla_reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paperinfo',
            name='vancouver_reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paperinfo',
            name='paper',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='papers.paper'),
        ),
    ]
