# Generated by Django 5.0.1 on 2024-07-20 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paperinfos', '0006_remove_paperinfo_reference_paperinfo_apa_reference_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paperinfo',
            old_name='apa_reference',
            new_name='APA',
        ),
        migrations.RenameField(
            model_name='paperinfo',
            old_name='chicago_reference',
            new_name='Chicago',
        ),
        migrations.RenameField(
            model_name='paperinfo',
            old_name='mla_reference',
            new_name='MLA',
        ),
        migrations.RenameField(
            model_name='paperinfo',
            old_name='vancouver_reference',
            new_name='Vancouver',
        ),
    ]
