# Generated by Django 5.0.7 on 2024-07-22 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='untitled', max_length=255)),
                ('reference_type', models.CharField(choices=[('APA', 'APA'), ('Chicago', 'Chicago'), ('Vancouver', 'Vancouver'), ('MLA', 'MLA')], default='APA', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
