# Generated by Django 5.0.1 on 2024-07-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_assignment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='reference_type',
            field=models.CharField(choices=[('apa', 'APA'), ('chicago', 'Chicago'), ('vancouver', 'Vancouver'), ('mla', 'MLA')], default='apa', max_length=10),
        ),
    ]
