# Generated by Django 5.0.1 on 2024-07-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignment_reference_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='reference_type',
            field=models.CharField(choices=[('APA', 'APA'), ('Chicago', 'Chicago'), ('Vancouver', 'Vancouver'), ('MLA', 'MLA')], default='APA', max_length=10),
        ),
    ]
