# Generated by Django 5.0.7 on 2024-11-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_alter_assignment_name'),
        ('assignments', '0004_alter_assignment_reference_type'),
    ]

    operations = [
    ]
